### ISSUE TITLE
Add validation referrer links to the starter HTML

### ISSUE THREAD

**Issue by kklamberty** [UMM-CSci-3601/3601-lab1_HTML-CSS#24]
If we add a link like `http://jigsaw.w3.org/css-validator/check/referer` to the HTML then we will be able to click it and get validation information without a bunch of copy/paste nonsense.

**Comment by NicMcPhee** [comment]
I started off trying to add the "This is valid HTML" badges, but in fact it looks like [the Official Party Line at W3C is to no longer support the badges](https://stackoverflow.com/questions/36383923/how-to-get-the-badge-when-validating-html-in-the-w3c-validator) so I'm just going to go with links instead.

What (if anything) do we want to say about this in the write-up? We presumably _don't_ want them adding random validation links to their project web pages, so it seems we may need to say something?

**Comment by NicMcPhee** [comment]
Actually, @kklamberty – the link you provided doesn't appear to work for CSS validation anymore. 😢 

It looks like you have to specify the URL to your CSS file(s) when you construct the link. Since those will be different for each group, I’m not sure what we want to do here. The easy thing is to leave it out and validate by hand as we’ve done in the past. Alternatively we could require (in the lab tasks) that they update the URL so that it works for their CSS. We’d probably still need to at least check the links, though, to make sure that they actually updated them, in which case it’s about as easy to validate by hand.

For the moment I've just removed the CSS validation link (af2dd4d7c98c15252596662e90fe0f9937123921) and just left the HTML validation link in.

**Comment by NicMcPhee** [comment]
The links work even less well now – neither the HTML _nor_ the CSS link work. I'm going to change these to just be links to the validation tools and people can just paste in their HTML/CSS as appropriate.

**Comment by NicMcPhee** [comment]
Closed by 4ff435e
