### ISSUE TITLE
Explicitly require that pages resize appropriately

### ISSUE THREAD

**Issue by NicMcPhee** [UMM-CSci-3601/3601-lab1_HTML-CSS#29]
There should be something explicit both in the write-up and in the rubric that makes it clear that we expect pages to resize gracefully and look reasonable on mobile.

**Comment by kklamberty** [comment]
We also want to update the first of the three CSS files to use flexbox to better illustrate how to use it to generate responsive designs.

**Comment by NicMcPhee** [comment]
So I think #31 takes care of most of the code side of this (thanks @CMenne!), but we still need to do something with the write-up and rubric.

**Comment by kklamberty** [comment]
The rubric now says this is worth 8 points: "Usable, reasonable page (even when viewed on smaller mobile devices)
(links are easy to see, color combinations are pleasant, fonts are easy to read, looks reasonable even when resized)"

The lab tasks already say, "Your page must look reasonable in all standard browsers (recent Chrome, Firefox, Safari, IE, Edge) and adapt the layout so that elements remain accessible and visible when the window is resized.
Pro tip: Making web pages that can resize across many different screen sizes and devices is referred to as responsive web design. This is very important since more web views are happening on phones now than on computers. By using fancy styling and other tools to adjust how a web page looks, developers can make a single page that will look good on multiple screen sizes rather than constructing multiple designs for each type of device. To see how your page would look on some phones or tablets: Open your page in Chrome > right-click the page > click "inspect element" > click the little phone symbol in the top-left corner. This will show roughly what your site would look like on the chosen device. In Firefox, click on the Developer button and choose Responsive Design mode. Or just resize your browser window so that it's really narrow and see how it behaves."
