### ISSUE TITLE
Add documentation about creating a new project from Github in WebStorm

### ISSUE THREAD

**Issue by NicMcPhee** [UMM-CSci-3601/3601-lab1_HTML-CSS#8]
We don't explain anywhere how to create a new WebStorm project from a Github repo.

**Comment by joethe** [comment]
I'm assuming that, with the switch to IDEA (vs webstorm), we don't want this any more?

Do we want to include instructions for IDEA? Perhaps we want to keep the lab materials IDE agnostic if possible?

**Comment by kklamberty** [comment]
I think it is accurate that we don't want to include instructions for WebStorm, and I think it's also accurate that we don't want to say much about any particular IDE. In this case, since they will be using GitHub classroom, they will be checking this out from version control and not really making a new project, right?

**Comment by NicMcPhee** [comment]
Should we just mark this as closed? We don't really say much of anything about how to check out a repo and create a project from Intellij. We do cover this in Lab 0 (at least sorta), so maybe we don't need to care about it here?

Thoughts?

**Comment by kklamberty** [comment]
I agree that we don't need to address this issue anymore for the reasons described above. I will close it.
